package com.tts.subscriberlist1.subscriber;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.annotations.CreationTimestamp;

@Entity
public class Subscriber {

//	Fields go here (we have five attributes in the Subscriber class):
//	@Id sets the id as the primary key. 
//	@GeneratedValue allows that id to be generated by an underlying database
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private Long id;
	private String firstName;
	private String lastName;
	private String userName;
	
//	@Column Allows the SQL table to have column names that match up with the field names (like firstName, lastName, etc.)
	@Column
	
//	@CreationTimestamp allows the database to create a timestamp based on the date
	@CreationTimestamp
	private Date signedUp;
	
//	Empty constructor. Did not select any of the fields & deleted super() bc there is no parent class we're referring to.
	public Subscriber() {
		
	}

//	Constructors from the fields (omitting id):
public Subscriber(String firstName, String lastName, String userName, Date signedUp) {
	super();
	this.firstName = firstName;
	this.lastName = lastName;
	this.userName = userName;
	this.signedUp = signedUp;
}



// Getters and Setters. un-selected "setId" so that we never override an id that's assigned
public String getFirstName() {
	return firstName;
}

public void setFirstName(String firstName) {
	this.firstName = firstName;
}

public String getLastName() {
	return lastName;
}

public void setLastName(String lastName) {
	this.lastName = lastName;
}

public String getUserName() {
	return userName;
}

public void setUserName(String userName) {
	this.userName = userName;
}


public Date getSignedUp() {
	return signedUp;
}

public void setSignedUp(Date signedUp) {
	this.signedUp = signedUp;
}

public Long getId() {
	return id;
}



//Generated toString() method using all fields. This avoids printing the memory location of something when you'd rather print the contents of your table/array/etc.
@Override
public String toString() {
	return "Subscriber [id=" + id + ", firstName=" + firstName + ", lastName=" + lastName + ", userName=" + userName
			+ ", signedUp=" + signedUp + "]";
}


	

	
	
	
}
